version: "3"

networks:
  laravel:


services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./src:/code
    networks:
      - laravel

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel
    environment:
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER: crooz
      MYSQL_PASSWORD: strongrootpassword
      MYSQL_ROOT_PASSWORD: strongrootpassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
